### PR TITLE
Adding fits alignment

### PR DESCRIPTION
**Pull request by zemogle**
This incorporates FITS alignment package, which I've called `fits_align` (instead of `lco_alipy`). The code uses `astropy` for FITS handling and accessing the sources in the FITS files. This can work along side the existing `FITSIO` install (used in `fits2image`) but I've also made a branch of `fits2image` which exclusively uses astropy  (because I couldn't get FITSIO installed locally) - https://github.com/LCOGT/fits2image/tree/astropy

The only other dependencies are `PIL/PIllow` and `numpy` (managed to totally get rid of `scipy`!).

`fits_align` isn't in our local pypi because I couldn't work out how to make Jenkins build it, but you can test and build it from here - https://github.com/LCOGT/fits_align

### CODE REVIEW

**Comment by Fingel** [comment]
Hi, 
It's not really clear how we are supposed to install fits_align. Since this is a public project, perhaps you can upload it to the public PyPI if the internal one isn't working for you?

**Comment by zemogle** [comment]
`fits_align` has a `setup.py` file you can use for installation. Did it not work? I'll look into put it on the public PyPi. I just wasn't sure what the procedure was for getting Jenkins set up for it. Maybe @irasnyd  can help?

**Comment by zemogle** [comment]
I've now added `fits_align` to the public PyPi 😄 

https://pypi.org/project/fits-align/

**Comment by Fingel** [comment]
Sweet!
I was able to test it out easily and the improvement is clear: nice work! It's been deployed.
Thank you for the pull request!

**Comment by zemogle** [comment]
Boom

**Pull request merged**
